use crate::apis::configuration::Configuration;
use crate::apis::employee_service_api::{
    FetchEmployeeByIdParams, Employee,
};
use crate::propelauth::helpers::{is_valid_id, map_autogenerated_error};
use crate::propelauth::errors::ErrorsWithNotFound;

pub struct EmployeeService<'a> {
    pub(crate) config: &'a Configuration,
}

impl EmployeeService<'_> {

    pub async fn fetch_employee_by_id(
        &self,
        params: FetchEmployeeByIdParams,
    ) -> Result<Employee, ErrorsWithNotFound> {
        if !is_valid_id(&params.employee_id) {
            return Err(ErrorsWithNotFound::NotFound);
        }

        crate::apis::employee_service_api::fetch_employee_by_id(&self.config, params)
            .await
            .map_err(|err| {
                map_autogenerated_error(
                    err,
                    ErrorsWithNotFound::UnexpectedException,
                    |status_code, _| match status_code.as_u16() {
                        401 => ErrorsWithNotFound::InvalidApiKey,
                        429 => ErrorsWithNotFound::PropelAuthRateLimit,
                        404 => ErrorsWithNotFound::NotFound,
                        _ => ErrorsWithNotFound::UnexpectedException,
                    },
                )
            })
    }


}
