use crate::apis::configuration::Configuration;
use crate::apis::mfa_service_api::{
    StepUpMfaError, VerifySmsChallengeParams, VerifyStepUpGrantParams,
};
use crate::apis::Error;
use crate::models::{
    SendSmsCodeResponse, VerifySmsChallengeResponse,
};
use crate::propelauth::errors::VerifyStepUpTotpChallengeError;
use crate::propelauth::helpers::map_autogenerated_error;
use crate::models::VerifyTotpChallengeResponse;
use crate::apis::mfa_service_api::{SendSmsMfaCodeParams, VerifyTotpChallengeParams};

pub struct MfaService<'a> {
    pub(crate) config: &'a Configuration,
}

impl MfaService<'_> {
    pub async fn verify_step_up_totp_challenge(
        &self,
        params: VerifyTotpChallengeParams,
    ) -> Result<VerifyTotpChallengeResponse, VerifyStepUpTotpChallengeError> {
        let result =
            crate::apis::mfa_service_api::verify_step_up_totp_challenge(&self.config, params).await;

        match result {
            Ok(response) => Ok(response),
            Err(Error::ResponseError(response)) => {
                if response.status == 401 {
                    return Err(VerifyStepUpTotpChallengeError::InvalidApiKey);
                } else if response.status == 429 {
                    return Err(VerifyStepUpTotpChallengeError::PropelAuthRateLimit);
                }

                let error_response: Result<serde_json::Value, _> =
                    serde_json::from_str(&response.content);
                if let Ok(error_json) = error_response {
                    if let Some(error_code) = error_json.get("error_code").and_then(|v| v.as_str())
                    {
                        match error_code {
                            "user_not_found" => {
                                return Err(VerifyStepUpTotpChallengeError::UserNotFound)
                            }
                            "mfa_not_enabled" => {
                                return Err(VerifyStepUpTotpChallengeError::MfaNotEnabled)
                            }
                            "incorrect_mfa_code" => {
                                return Err(VerifyStepUpTotpChallengeError::IncorrectMfaCode)
                            }
                            "invalid_request_fields" => {
                                return Err(VerifyStepUpTotpChallengeError::BadRequest(
                                    response.content,
                                ))
                            }
                            "feature_gated" => {
                                return Err(VerifyStepUpTotpChallengeError::FeatureGated)
                            }
                            _ => {}
                        }
                    }
                }

                Err(VerifyStepUpTotpChallengeError::UnexpectedException)
            }
            Err(_) => Err(VerifyStepUpTotpChallengeError::UnexpectedException),
        }
    }

    pub async fn verify_step_up_grant(
        &self,
        params: VerifyStepUpGrantParams,
    ) -> Result<crate::models::SuccessfulResponse, StepUpMfaError> {
        crate::apis::mfa_service_api::verify_step_up_grant(&self.config, params)
            .await
            .map_err(|err| {
                map_autogenerated_error(
                    err,
                    StepUpMfaError::UnexpectedExceptionWithSDK,
                    |status_code, _| match status_code.as_u16() {
                        401 => StepUpMfaError::InvalidIntegrationAPIKey,
                        429 => StepUpMfaError::PropelAuthRateLimit,
                        404 => StepUpMfaError::NotFound,
                        _ => StepUpMfaError::UnexpectedExceptionWithSDK,
                    },
                )
            })
    }

    pub async fn send_sms_mfa_code(
        &self,
        params: SendSmsMfaCodeParams,
    ) -> Result<SendSmsCodeResponse, StepUpMfaError> {
        crate::apis::mfa_service_api::send_sms_mfa_code(&self.config, params)
            .await
            .map_err(|err| {
                map_autogenerated_error(
                    err,
                    StepUpMfaError::UnexpectedExceptionWithSDK,
                    |status_code, _| match status_code.as_u16() {
                        401 => StepUpMfaError::InvalidIntegrationAPIKey,
                        429 => StepUpMfaError::PropelAuthRateLimit,
                        404 => StepUpMfaError::NotFound,
                        _ => StepUpMfaError::UnexpectedExceptionWithSDK,
                    },
                )
            })
    }

    pub async fn verify_sms_challenge(
        &self,
        params: VerifySmsChallengeParams,
    ) -> Result<VerifySmsChallengeResponse, StepUpMfaError> {
        crate::apis::mfa_service_api::verify_sms_challenge(&self.config, params)
            .await
            .map_err(|err| {
                map_autogenerated_error(
                    err,
                    StepUpMfaError::UnexpectedExceptionWithSDK,
                    |status_code, _| match status_code.as_u16() {
                        401 => StepUpMfaError::InvalidIntegrationAPIKey,
                        429 => StepUpMfaError::PropelAuthRateLimit,
                        404 => StepUpMfaError::NotFound,
                        _ => StepUpMfaError::UnexpectedExceptionWithSDK,
                    },
                )
            })
    }
}
