use crate::apis::configuration::Configuration;
use crate::models::{
    FetchOrgScimGroupsRequest, FetchScimGroupRequest,
    ScimGroup, ScimGroupResultPage,
};
use crate::propelauth::helpers::{is_valid_id, map_autogenerated_error};
use crate::propelauth::errors::ErrorsWithNotFound;

pub struct ScimService<'a> {
    pub(crate) config: &'a Configuration,
}

impl ScimService<'_> {

    pub async fn fetch_org_scim_groups(
        &self,
        params: FetchOrgScimGroupsRequest,
    ) -> Result<ScimGroupResultPage, ErrorsWithNotFound> {
        if !is_valid_id(&params.org_id) {
            return Err(ErrorsWithNotFound::NotFound);
        }

        crate::apis::scim_service_api::fetch_org_scim_groups(&self.config, params)
            .await
            .map_err(|err| {
                map_autogenerated_error(
                    err,
                    ErrorsWithNotFound::UnexpectedException,
                    |status_code, _| match status_code.as_u16() {
                        401 => ErrorsWithNotFound::InvalidApiKey,
                        429 => ErrorsWithNotFound::PropelAuthRateLimit,
                        404 => ErrorsWithNotFound::NotFound,
                        _ => ErrorsWithNotFound::UnexpectedException,
                    },
                )
            })
    }

    pub async fn fetch_scim_group(
        &self,
        params: FetchScimGroupRequest,
    ) -> Result<ScimGroup, ErrorsWithNotFound> {
        if !is_valid_id(&params.org_id) {
            return Err(ErrorsWithNotFound::NotFound);
        }

        crate::apis::scim_service_api::fetch_scim_group(&self.config, params)
            .await
            .map_err(|err| {
                map_autogenerated_error(
                    err,
                    ErrorsWithNotFound::UnexpectedException,
                    |status_code, _| match status_code.as_u16() {
                        401 => ErrorsWithNotFound::InvalidApiKey,
                        429 => ErrorsWithNotFound::PropelAuthRateLimit,
                        404 => ErrorsWithNotFound::NotFound,
                        _ => ErrorsWithNotFound::UnexpectedException,
                    },
                )
            })
    }

}
