/*
 * propelauth
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use reqwest;

use super::{configuration, Error};
use crate::propelauth::auth::AUTH_HOSTNAME_HEADER;
use crate::apis::ResponseContent;

/// struct for passing parameters to the method [`fetch_employee_by_id`]
#[derive(Clone, Debug, Default)]
pub struct FetchEmployeeByIdParams {
    pub employee_id: String,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Employee {
    #[serde(rename = "email")]
    pub email: String,
}

/// struct for typed errors of method [`fetch_employee_by_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchEmployeeByIdError {
    Status401(serde_json::Value),
    Status404(serde_json::Value),
    UnknownValue(serde_json::Value),
}


pub async fn fetch_employee_by_id(
    configuration: &configuration::Configuration,
    params: FetchEmployeeByIdParams,
) -> Result<Employee, Error<FetchEmployeeByIdError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let employee_id = params.employee_id;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!(
        "{}/api/backend/v1/employee/{employee_id}",
        local_var_configuration.base_path,
        employee_id = crate::apis::urlencode(employee_id)
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.header(
        AUTH_HOSTNAME_HEADER,
        local_var_configuration.auth_hostname.to_owned(),
    );

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<FetchEmployeeByIdError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error: crate::apis::ResponseContent<FetchEmployeeByIdError> = ResponseContent {
            status: local_var_status,
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

