/*
 * propelauth
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use reqwest;

use super::{configuration, Error};
use crate::apis::ResponseContent;
use crate::models::reports::{
    FetchReportQuery, OrgReport, OrgReportType, UserReportPage, UserReportType,
};
use crate::propelauth::auth::AUTH_HOSTNAME_HEADER;

/// struct for typed errors of methods [`fetch_user_report`] or [`fetch_org_report`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchReportRequestError {
    Status401(serde_json::Value),
    Status400(serde_json::Value),
    Status429(serde_json::Value),
    UnknownValue(serde_json::Value),
}

pub(crate) async fn fetch_user_report(
    configuration: &configuration::Configuration,
    report_key: UserReportType,
    params: FetchReportQuery,
) -> Result<UserReportPage, Error<FetchReportRequestError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!(
        "{}/api/backend/v1/user_report/{report_key}",
        local_var_configuration.base_path,
        report_key = report_key.as_str(),
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    local_var_req_builder = local_var_req_builder.query(&params);

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.header(
        AUTH_HOSTNAME_HEADER,
        local_var_configuration.auth_hostname.to_owned(),
    );

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<FetchReportRequestError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error: crate::apis::ResponseContent<FetchReportRequestError> =
            ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
        Err(Error::ResponseError(local_var_error))
    }
}

pub(crate) async fn fetch_org_report(
    configuration: &configuration::Configuration,
    report_key: OrgReportType,
    params: FetchReportQuery,
) -> Result<OrgReport, Error<FetchReportRequestError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!(
        "{}/api/backend/v1/org_report/{report_key}",
        local_var_configuration.base_path,
        report_key = report_key.as_str(),
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    local_var_req_builder = local_var_req_builder.query(&params);

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.header(
        AUTH_HOSTNAME_HEADER,
        local_var_configuration.auth_hostname.to_owned(),
    );

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<FetchReportRequestError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error: crate::apis::ResponseContent<FetchReportRequestError> =
            ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
        Err(Error::ResponseError(local_var_error))
    }
}
