/*
 * propelauth
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

#[cfg(feature = "schemars09")]
use {
    std::convert::TryFrom,
    schemars09 as schemars,
};
#[cfg(any(feature = "schemars09", feature = "schemars-latest"))]
use schemars::JsonSchema;


#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
#[cfg_attr(any(feature = "schemars09", feature = "schemars-latest"), derive(JsonSchema))]
pub struct BadFetchUsersInOrgQuery {
    #[serde(rename = "page_size", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<Vec<String>>,
    #[serde(rename = "page_number", skip_serializing_if = "Option::is_none")]
    pub page_number: Option<Vec<String>>,
}

impl BadFetchUsersInOrgQuery {
    pub fn new() -> BadFetchUsersInOrgQuery {
        BadFetchUsersInOrgQuery {
            page_size: None,
            page_number: None,
        }
    }
}


