/*
 * propelauth
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

#[cfg(any(feature = "schemars09", feature = "schemars-latest"))]
use schemars::JsonSchema;
#[cfg(feature = "schemars09")]
use std::convert::TryFrom;


#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
#[cfg_attr(any(feature = "schemars09", feature = "schemars-latest"), derive(JsonSchema))]
pub struct BadUpdateUserEmailRequest {
    #[serde(rename = "new_email", skip_serializing_if = "Option::is_none")]
    pub new_email: Option<Vec<String>>,
}

impl BadUpdateUserEmailRequest {
    pub fn new() -> BadUpdateUserEmailRequest {
        BadUpdateUserEmailRequest {
            new_email: None,
        }
    }
}


