/*
 * propelauth
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

#[cfg(feature = "schemars09")]
use {
    std::convert::TryFrom,
    schemars09 as schemars,
};
#[cfg(any(feature = "schemars09", feature = "schemars1"))]
use schemars::JsonSchema;


#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
#[cfg_attr(any(feature = "schemars09", feature = "schemars1"), derive(JsonSchema))]
pub struct BadFetchUsersByIdsQuery {
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<Vec<String>>,
}

impl BadFetchUsersByIdsQuery {
    pub fn new() -> BadFetchUsersByIdsQuery {
        BadFetchUsersByIdsQuery {
            query: None,
        }
    }
}


