/*
 * propelauth
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BadUpdateUserEmailRequest {
    #[serde(rename = "new_email", skip_serializing_if = "Option::is_none")]
    pub new_email: Option<Vec<String>>,
}

impl BadUpdateUserEmailRequest {
    pub fn new() -> BadUpdateUserEmailRequest {
        BadUpdateUserEmailRequest { new_email: None }
    }
}
