/*
 * propelauth
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.6
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BadFetchUsersByUsernamesQuery {
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<Vec<String>>,
}

impl BadFetchUsersByUsernamesQuery {
    pub fn new() -> BadFetchUsersByUsernamesQuery {
        BadFetchUsersByUsernamesQuery {
            query: None,
        }
    }
}


