/*
 * propelauth
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

#[cfg(feature = "schemars09")]
use {
    std::convert::TryFrom,
    schemars09 as schemars,
};
#[cfg(any(feature = "schemars09", feature = "schemars1"))]
use schemars::JsonSchema;


#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
#[cfg_attr(any(feature = "schemars09", feature = "schemars1"), derive(JsonSchema))]
pub struct CreateMagicLinkRequest {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "redirect_to_url", skip_serializing_if = "Option::is_none")]
    pub redirect_to_url: Option<String>,
    #[serde(rename = "expires_in_hours", skip_serializing_if = "Option::is_none")]
    pub expires_in_hours: Option<i64>,
    #[serde(rename = "create_new_user_if_one_doesnt_exist", skip_serializing_if = "Option::is_none")]
    pub create_new_user_if_one_doesnt_exist: Option<bool>,
    #[serde(rename = "expire_after_first_use", skip_serializing_if = "Option::is_none")]
    pub expire_after_first_use: Option<bool>,
}

impl CreateMagicLinkRequest {
    pub fn new(email: String) -> CreateMagicLinkRequest {
        CreateMagicLinkRequest {
            email,
            redirect_to_url: None,
            expires_in_hours: None,
            create_new_user_if_one_doesnt_exist: None,
            expire_after_first_use: None,
        }
    }
}


