/*
 * propelauth
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */
use std::collections::HashMap;



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateMagicLinkRequest {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "redirect_to_url", skip_serializing_if = "Option::is_none")]
    pub redirect_to_url: Option<String>,
    #[serde(rename = "expires_in_hours", skip_serializing_if = "Option::is_none")]
    pub expires_in_hours: Option<i64>,
    #[serde(rename = "create_new_user_if_one_doesnt_exist", skip_serializing_if = "Option::is_none")]
    pub create_new_user_if_one_doesnt_exist: Option<bool>,
    #[serde(rename = "expire_after_first_use", skip_serializing_if = "Option::is_none")]
    pub expire_after_first_use: Option<bool>,
    #[serde(rename = "requires_interstitial", skip_serializing_if = "Option::is_none")]
    pub requires_interstitial: Option<bool>,
    #[serde(rename = "user_signup_query_parameters", skip_serializing_if = "Option::is_none")]
    pub user_signup_query_parameters: Option<HashMap<String, String>>,
}

impl CreateMagicLinkRequest {
    pub fn new(email: String) -> CreateMagicLinkRequest {
        CreateMagicLinkRequest {
            email,
            redirect_to_url: None,
            expires_in_hours: None,
            create_new_user_if_one_doesnt_exist: None,
            expire_after_first_use: None,
            requires_interstitial: None,
            user_signup_query_parameters: None
        }
    }
}
