/*
 * propelauth
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MagicLink {
    #[serde(rename = "url")]
    pub url: String,
}

impl MagicLink {
    pub fn new(url: String) -> MagicLink {
        MagicLink { url }
    }
}
