/*
 * propelauth
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MigrateUserPasswordRequest {
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "password_hash")]
    pub password_hash: String,
}

impl MigrateUserPasswordRequest {
    pub fn new(user_id: String, password_hash: String) -> MigrateUserPasswordRequest {
        MigrateUserPasswordRequest {
            user_id,
            password_hash,
        }
    }
}
