/*
 * propelauth
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[cfg(feature = "schemars09")]
use {
    std::convert::TryFrom,
    schemars09 as schemars,
};
#[cfg(any(feature = "schemars09", feature = "schemars1"))]
use schemars::JsonSchema;

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
#[cfg_attr(any(feature = "schemars09", feature = "schemars1"), derive(JsonSchema))]
pub struct RevokePendingOrgInviteRequest {
    #[serde(rename = "org_id")]
    pub org_id: String,
    #[serde(rename = "invitee_email")]
    pub invitee_email: String,
}

impl RevokePendingOrgInviteRequest {
    pub fn new(org_id: String, invitee_email: String) -> RevokePendingOrgInviteRequest {
        RevokePendingOrgInviteRequest {
            org_id,
            invitee_email,
        }
    }
}
