/*
 * propelauth
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// struct for passing parameters to the method [`fetch_org_scim_groups`]
#[derive(Clone, Debug, Default)]
pub struct FetchOrgScimGroupsRequest {
    pub org_id: String,
    pub user_id: Option<String>,
    pub page_size: Option<i64>,
    pub page_number: Option<i64>,
}

/// struct for passing parameters to the method [`fetch_scim_group`]
#[derive(Clone, Debug, Default)]
pub struct FetchScimGroupRequest {
    pub org_id: String,
    pub group_id: String,
    pub members_page_size: Option<i64>,
    pub members_page_number: Option<i64>,
}
