/*
 * propelauth
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdatePasswordRequest {
    #[serde(rename = "password")]
    pub password: String,
}

impl UpdatePasswordRequest {
    pub fn new(password: String) -> UpdatePasswordRequest {
        UpdatePasswordRequest { password }
    }
}
