/*
 * propelauth
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateEmailRequest {
    #[serde(rename = "new_email")]
    pub new_email: String,
    #[serde(rename = "require_email_confirmation")]
    pub require_email_confirmation: bool,
}

impl UpdateEmailRequest {
    pub fn new(new_email: String, require_email_confirmation: bool) -> UpdateEmailRequest {
        UpdateEmailRequest {
            new_email,
            require_email_confirmation,
        }
    }
}
