/*
 * propelauth
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

#[cfg(feature = "schemars09")]
use {
    std::convert::TryFrom,
    schemars09 as schemars,
};
#[cfg(any(feature = "schemars09", feature = "schemars-latest"))]
use schemars::JsonSchema;


#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
#[cfg_attr(any(feature = "schemars09", feature = "schemars-latest"), derive(JsonSchema))]
pub struct UserPagedResponse {
    #[serde(rename = "users")]
    pub users: Vec<crate::models::UserMetadata>,
    #[serde(rename = "total_users")]
    pub total_users: i64,
    #[serde(rename = "current_page")]
    pub current_page: i64,
    #[serde(rename = "page_size")]
    pub page_size: i64,
    #[serde(rename = "has_more_results")]
    pub has_more_results: bool,
}

impl UserPagedResponse {
    pub fn new(users: Vec<crate::models::UserMetadata>, total_users: i64, current_page: i64, page_size: i64, has_more_results: bool) -> UserPagedResponse {
        UserPagedResponse {
            users,
            total_users,
            current_page,
            page_size,
            has_more_results,
        }
    }
}


