/*
 * propelauth
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

#[cfg(any(feature = "schemars09", feature = "schemars-latest"))]
use schemars::JsonSchema;
#[cfg(feature = "schemars09")]
use std::convert::TryFrom;


#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
#[cfg_attr(any(feature = "schemars09", feature = "schemars-latest"), derive(JsonSchema))]
pub struct UserIdsQuery {
    #[serde(rename = "user_ids")]
    pub user_ids: Vec<String>,
}

impl UserIdsQuery {
    pub fn new(user_ids: Vec<String>) -> UserIdsQuery {
        UserIdsQuery {
            user_ids,
        }
    }
}


